### ISSUE TITLE
Consider converting to camel case with acronyms

### ISSUE THREAD

**Issue by negz** [crossplane-contrib/terrajet#13]
https://github.com/iancoleman/strcase#custom-acronyms-for-tocamel--tolowercamel

If we're needing to translate snake case Terraform fields to camel case, it may be nice to teach our translation code a few common acronyms so it can capitalize them correctly. That said - in same cases (e.g. AWS) I recall that they don't capitalize acronyms so perhaps it's better to just match their API as closely as possible there. 🤷

**Comment by muvaf** [comment]
Yes, this was the reason I wanted to use that library. We'll [add](https://github.com/crossplane-contrib/terrajet/issues/13) a conservative `init()` in terrajet and let provider developer add their own list as well.

**Comment by muvaf** [comment]
Closing in favor of https://github.com/crossplane-contrib/terrajet/issues/15
