### ISSUE TITLE
Allow Configuring Markers/Comments on Generated CRD Spec Fields

### ISSUE THREAD

**Issue by ulucinar** [crossplane-contrib/terrajet#140]
### What problem are you facing?

As @vfarcic suggested in https://github.com/crossplane-contrib/provider-tf-azure/issues/79, we can consider extending our resource configuration interface (`pkg/config`) with means of being able to introduce markers/comments on the generated fields/types. This looks also related to #92, although the latter is about generating automatic documentation. But in #92, we had better also provide means of manual overrides.

### How could Terrajet help solve your problem?

Add new configuration interface for field/type comments/markers.

**Comment by muvaf** [comment]
Today we can achieve this by adding the comment produced with [this utility](https://github.com/crossplane-contrib/terrajet/blob/main/pkg/types/comments/comment.go) to the `Description` property of the given field in the schema. We're using it for reference markers but it's generic that you can add anything you'd like.

**Comment by muvaf** [comment]
Closing this as you can achieve the behavior by manipulating `Description` of the schema that's available in the configurator. Feel free to reopen if that doesn't work for you.
