### ISSUE TITLE
Add known special acronyms to init

### ISSUE THREAD

**Issue by muvaf** [crossplane-contrib/terrajet#15]
The library we use to do camel case conversions [allow](https://github.com/iancoleman/strcase/#custom-acronyms-for-tocamel--tolowercamel) customization by adding acronyms in `init()`. We should have a default set of custom acronyms (like DNS, IPv6, ID etc) and let providers add their own if need be.

**Comment by muvaf** [comment]
Ugh, it turns out it [doesn't run](https://github.com/iancoleman/strcase/blob/692d1b8/camel.go#L38) the checker for every word in the string; it just acts like an override map. I'll have to implement a converter for `snake_field to CamelCase`.

**Comment by muvaf** [comment]
Hmm Kubernetes resources do appear to care about this, there is `status.podIP` field in `Pod`.

**Comment by negz** [comment]
> I'm having some second thoughts about whether we should do this for json tags

The goal is to match the cloud APIs as closely as possible, so I actually think not doing this for JSON tags might make sense in a lot of cases. For example I believe AWS APIs typically use JSON struct fields like `vpcId` or `someArn`, not `vpcID` and `someARN`. I thiiiiink GCP is like this too - I just checked https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1/instances#DatabaseInstance and I see `secondaryGceZone` not `secondaryGCEZone`.

It would still be nice to correctly capitalise the actual Go struct fields in our types, in accordance with typical Go style. I could be convinced it's not the end of the world if it's not possible to do that though - there's plenty of precedent for relaxing style on generated code that humans don't need to interface with as often.
