### ISSUE TITLE
Optional sensitive fields are not supported

### ISSUE THREAD

**Issue by displague** [crossplane-contrib/terrajet#161]
### What happened?

First reported in https://github.com/crossplane-contrib/provider-tf-equinix-metal/issues/8, fields that are optional and sensitive in the Terraform provider will not prevent resource creation but will cause errors when the resource is being refreshed - thus preventing deletion.

In the Equinix Metal provider's `metal_device` resource, optional sensitive fields `userdata` and `custom_data` are set on device create are not refreshed on subsequent reads. These fields are not forcenew.

https://github.com/equinix/terraform-provider-metal/blob/main/metal/resource_metal_device.go#L268-L282

In Terraform, these fields may appear to be `null` in the `terraform.state` `resources[*].instances[*].attributes` map.

When encountering these values, Terrajet errors out (with a warning): 
```
Warning  CannotObserveExternalResource  30m                  
managed/device.equinixmetal.jet.crossplane.io/v1alpha1, kind=device  
cannot get connection details: cannot get connection details: 
cannot not get a string for fieldpath "user_data": user_data: not a string
```
https://github.com/crossplane-contrib/terrajet/blob/6abd89a444231a61237788434f38d6e92dbae150/pkg/resource/sensitive.go#L119

### How can we reproduce it?

Attempt to create and then delete the following resource: 
https://github.com/crossplane-contrib/provider-tf-equinix-metal/blob/main/examples/device/device.yaml

Or, attempt to delete any resource with an optional sensitive attribute value that has no assigned value.

**Comment by muvaf** [comment]
@displague  Could this be same as https://github.com/crossplane-contrib/terrajet/issues/118 ?

**Comment by displague** [comment]
@muvaf The descriptions sound similar, the problem I am running into is at observation time, I can't tell if the problem in #118 was in any way focused on parsing the schema and defining creations parameters.

The conversation in https://github.com/crossplane-contrib/terrajet/pull/149/files#r751621390 makes me wonder if there are some edge-cases to consider. 

In the AWS and GCP provider, perhaps the values returned are empty strings rather than nil?

**Comment by muvaf** [comment]
@turkenh would you mind taking a look?
