### ISSUE TITLE
Create provider-tf-template

### ISSUE THREAD

**Issue by muvaf** [crossplane-contrib/terrajet#60]
### What problem are you facing?

Terrajet providers have different `Dockerfile` and several other things that we need to do lots of manual plumbing to make provider-template work.

### How could Terrajet help solve your problem?

We can have a `provider-tf-template` people could just use to bootstrap a Terrajet-based provider.

**Comment by muvaf** [comment]
Since we'll be doing two Terrajet-generated provider releases, we'll be able to go through all details of this. So I'll tackle this issue today even though it's marked as `beta`, not to go back and load all that context again later.

**Comment by turkenh** [comment]
Closing since https://github.com/crossplane-contrib/provider-tf-template is ready for use.
