### ISSUE TITLE
Sensitive data leaks at `status.atProvider` and the "tf.crossplane.io/state" annotation

### ISSUE THREAD

**Issue by ulucinar** [crossplane-contrib/terrajet#65]
### What happened?

When testing provider-tf-azure's `KubernetesCluster` MR, we have observed that provisioned cluster's credentials, e.g. KubeConfig, are available in the Teffaform state as regular fields. An example is:
```json
{
  "version": 4,
  "terraform_version": "1.0.5",
  "serial": 3,
  "lineage": "365fcd38-09a3-e30a-cb02-df3117306af0",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "azurerm_kubernetes_cluster",
      "name": "example",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
...
            "kube_config": [
              {
                "client_certificate":
```

Because these attributes are resource dependent, we need to be able to treat them as credentials in a resource specific manner. It looks like in the Terraform provider resource schema, such fields are marked as `sensitive`, like [kube_config_raw](https://github.com/hashicorp/terraform-provider-azurerm/blob/d347dedf86f382a5a614710aa41ab6445b8519f9/internal/services/containers/kubernetes_cluster_resource.go#L869), or [kube_config.password](https://github.com/hashicorp/terraform-provider-azurerm/blob/d347dedf86f382a5a614710aa41ab6445b8519f9/internal/services/containers/kubernetes_cluster_resource.go#L845).

Those fields that are marked as `sensitive` are also good candidates for being part of the [connection secrets](https://github.com/crossplane-contrib/terrajet/issues/35). 

### How can we reproduce it?

Provisioning a `KubernetesCluster` using https://github.com/crossplane-contrib/provider-tf-azure/blob/258830e0bc0627f2749bcd7e285e3c831849a04a/examples/kubernetes/kubernetescluster.yaml reveals the issue.

**Comment by muvaf** [comment]
I think https://github.com/crossplane-contrib/terrajet/issues/35 would cover this. Closing. Please reopen if that's not the case.
