### ISSUE TITLE
Add Instructions

### ISSUE THREAD

**Issue by luebken** [crossplane-contrib/terrajet#75]
### What problem are you facing?
The current readme doesn't provide any instructions on how to get started. 

### How could Terrajet help solve your problem?
We should provide an overview on how Terrjet works and a getting started on how to generate a Crossplane provider based on a Terraform provider.

**Comment by muvaf** [comment]
@luebken is this covered by https://github.com/crossplane-contrib/terrajet/issues/42 ?

**Comment by luebken** [comment]
yes
