### ISSUE TITLE
Use tf attribute names in path specifications for late-initialization filters

### ISSUE THREAD

**Issue by ulucinar** [crossplane-contrib/terrajet#87]
### What problem are you facing?

Please see the comment https://github.com/crossplane-contrib/terrajet/pull/85#issuecomment-937523984 for the context. I believe it makes sense to provide a more consistent developer experience while authoring resource configurations for Terrajet-based resources.

### How could Terrajet help solve your problem?

We could use the `Paved` syntax with tf attribute names as path elements.

**Comment by turkenh** [comment]
Closed with https://github.com/crossplane-contrib/terrajet/pull/128
