### ISSUE TITLE
Allow overriding the group and version of a type

### ISSUE THREAD

**Issue by muvaf** [crossplane-contrib/terrajet#97]
### What problem are you facing?

Currently, we're able to override `kind` but not `group`.

### How could Terrajet help solve your problem?

See how we can enable this so that for example `aws_vpc` resource could go to `ec2` group with `VPC` kind name, which is where it should live but lives under `aws_vpc` for historical reasons in Terraform.

**Comment by turkenh** [comment]
Closed with: https://github.com/crossplane-contrib/terrajet/pull/128
